MS-06: Positions - Components
BaSD-2021/German-MindSet-app pull request #1
Opened 2021-11-26 23:25 UTC by nicolasblasco

2021-11-30 20:54 UTC, ValentinaCollareta requested changes

2021-11-30 20:54 UTC, ValentinaCollareta commented on src/Components/Positions/index.js
> +  const [error, setError] = useState('');
It would be necessary to add a modal of success when the position is deleted

2021-11-30 20:54 UTC, ValentinaCollareta commented on src/Components/Positions/Modal/index.js
> +          <Button label={'Confirm'} onClick={props.onConfirm} />
I think it is not necessary to have a "confirm" and a "close" in the modal success and error, if they appear and then the page is refreshed or disappears to correct the errors, that would be fine !

2021-12-01 18:52 UTC, ValentinaCollareta approved these changes
Next time it would be nice to add a cursor: pointer to the buttons, but it's fine anyway!

2021-12-01 19:05 UTC, estefrare requested changes

2021-12-01 19:05 UTC, estefrare commented on src/Components/Positions/Form/index.js
> +          <Button type={'submit'} label={'Confirm'} onClick={onSubmit} />
```suggestion
          <Button type={'submit'} label={'Confirm'} />
```

2021-12-03 02:15 UTC, estefrare approved these changes

2021-12-03 03:54 UTC, GuidoGlielmi approved these changes
GOOD WORK!

2021-12-03 03:55 UTC, merged