MS-05: Interviews - Components
BaSD-2021/German-MindSet-app pull request #2
Opened 2021-11-27 16:18 UTC by ValentinaCollareta

* Make a GET request to bring all the interviews &  create a table/list component to show them

2021-11-30 18:58 UTC, nicolasblasco commented
@ValentinaCollareta Review of deployment;
- Problems to create an interview -> The server return a HTTP 400 Bad Request
- In the form, we could use a select instead of an input the status
- We should show a modal in a message with success or error
- We should refresh the page and close the modal when we delete an interview

2021-11-30 19:06 UTC, ValentinaCollareta commented
Hola

2021-11-30 19:10 UTC, ValentinaCollareta commented
@nicolasblasco I don't have any problem to create a new Interview ! 😕  Also, the page is refreshed after delete an interview ! For the rest, I'm working on it 👍

2021-11-30 19:18 UTC, nicolasblasco commented
@ValentinaCollareta I tried again and it works! 
We should only focus on the other problems then!

2021-12-01 18:45 UTC, nicolasblasco approved these changes

2021-12-01 19:44 UTC, estefrare requested changes

2021-12-01 19:44 UTC, estefrare commented on .eslintrc.json
> +      "no-unused-vars": "off"
```suggestion
      "no-unused-vars": "warn"
```

2021-12-01 19:44 UTC, estefrare commented on src/Components/Interviews/EditForm/index.js
> +        <button type="submit" className={styles.confirm} onClick={onSubmit}>
```suggestion
        <button type="submit" className={styles.confirm}>
```

2021-12-01 19:44 UTC, estefrare commented on src/Components/Interviews/EditForm/index.js
> +          style={{ color: 'red', width: '200px', textAlign: 'center', float: 'right' }}
DO NOT USE LINE STYLES

2021-12-01 19:44 UTC, estefrare commented on src/Components/Interviews/index.js
> +            />
this modal should be outside the map iteration

2021-12-01 19:44 UTC, estefrare commented on src/Components/Interviews/index.js
> +      })
refactor this

2021-12-03 02:15 UTC, estefrare approved these changes

2021-12-03 03:59 UTC, nicolasblasco approved these changes

2021-12-03 11:18 UTC, merged