BaSD-MS-48: implement react final form in psychologists and profiles
BaSD-2021/German-MindSet-app pull request #48
Opened 2021-12-19 05:45 UTC by GuidoGlielmi

2021-12-20 13:23 UTC, nicolasblasco commented on src/Components/Admin/Profiles/Form/index.js
> +        /[A-Za-z ]+/ || formValues.profile?.length < 3 || formValues.profile?.length > 30
@GuidoGlielmi length validation isn't working, we should fix this

2021-12-20 13:27 UTC, nicolasblasco commented on src/Components/Admin/Psychologists/Form/index.js
> +  };
@GuidoGlielmi we should validate address and could also validate password and username. We could follow the same validations made in admins for password and username, and sessions for the address

2021-12-20 13:28 UTC, nicolasblasco commented
@GuidoGlielmi we could validate the availability by validating that if a day is checked, the from a to can't be 0. And if it is not checked the from and to have to be 0.

2021-12-20 13:29 UTC, nicolasblasco requested changes
@GuidoGlielmi implementation of final form is very good but we should see the comments requested to approve this PR

2021-12-21 18:10 UTC, nicolasblasco commented
@GuidoGlielmi username validation isn't working in psychologists component. It should be required

2021-12-21 18:15 UTC, nicolasblasco commented on src/Components/Admin/Psychologists/Form/index.js
> +  };
@GuidoGlielmi we should change the braces {} for parenthesis for the function to work

2021-12-21 20:25 UTC, ValentinaCollareta approved these changes

2021-12-22 02:10 UTC, nicolasblasco approved these changes

2021-12-22 02:10 UTC, merged