BaSD-MS-51: Implement React Final Form In Clients
BaSD-2021/German-MindSet-app pull request #49
Opened 2021-12-19 20:16 UTC by luisnannini

*Edit Clients form to include Final Form logic

2021-12-20 02:25 UTC, GuidoGlielmi reviewed
Update development branch and merge it into your branch so vercel accepts it

2021-12-20 13:10 UTC, nicolasblasco commented on src/Components/Admin/Clients/Form/index.js
> +  // };
@luisnannini we should erase commented code

2021-12-20 13:14 UTC, nicolasblasco commented on src/Components/Admin/Clients/Form/index.js
> +      errors.country = 'School must contain at least 5 characters';
@luisnannini we should change school to be country and maybe be at least 3 characters

2021-12-20 13:14 UTC, nicolasblasco commented on src/Components/Admin/Clients/Form/index.js
> +      errors.country = 'School must be less than 50 characters';
@luisnannini we should change school to be country

2021-12-20 13:15 UTC, nicolasblasco commented on src/Components/Admin/Clients/Form/index.js
> +
@luisnannini we should also add a validation for the description

2021-12-20 13:15 UTC, nicolasblasco commented on src/Components/Admin/Clients/Form/index.js
> +              <ButtonConfirm disabled={isLoading} type="submit" />
@luisnannini we should change disabled to have formProps submitting a pristine

2021-12-20 13:16 UTC, nicolasblasco requested changes
@luisnannini implementation of final form is very good, but we should see the comments requested before approving

2021-12-20 13:30 UTC, nicolasblasco commented on src/Components/Admin/Clients/Form/index.js
> +                  disabled={isLoading}
@luisnannini we should change disabled to have formProps.submitting (in all fields)

2021-12-20 20:48 UTC, nicolasblasco approved these changes

2021-12-21 18:02 UTC, ValentinaCollareta approved these changes

2021-12-21 18:05 UTC, merged