BaSD-MS-04: Clients - Components
BaSD-2021/German-MindSet-app pull request #5
Opened 2021-11-29 23:59 UTC by agustin-schiaffino

2021-12-01 17:04 UTC, estefrare requested changes

2021-12-01 22:33 UTC, nicolasblasco commented on src/Components/Clients/Form/index.js
> +    }
@agustin-schiaffino maybe we should add setLoading(false) so it can change isLoading. 
If clientId doesn't exist we never enter the if and it will always be true.

2021-12-03 02:16 UTC, estefrare approved these changes

2021-12-03 04:03 UTC, nicolasblasco approved these changes

2021-12-03 04:12 UTC, merged