BaSD-MS-47: Implement react final form in postulants and sessions
BaSD-2021/German-MindSet-app pull request #51
Opened 2021-12-20 13:48 UTC by nicolasblasco

[DRAFT]

2021-12-21 01:08 UTC, ValentinaCollareta requested changes

2021-12-21 01:08 UTC, ValentinaCollareta commented on src/Components/Admin/Postulants/Form/index.js
> +                    initialValue={values.available ? contactRange.from : '00:00'}
Shouldn't it be like
initialValue={values.available ? contactRange**.to** : '00:00' ?

2021-12-22 02:11 UTC, PabloMBernal approved these changes

2021-12-22 02:13 UTC, agustin-schiaffino approved these changes

2021-12-22 02:16 UTC, ValentinaCollareta approved these changes

2021-12-22 02:23 UTC, merged